#1
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, SALARY FROM Employees
	WHERE SALARY NOT BETWEEN 10000 AND 15000;

#2
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, Departments.DEPARTMENT_ID FROM Employees
	INNER JOIN Departments ON Employees.DEPARTMENT_ID = Departments.DEPARTMENT_ID
    WHERE Departments.DEPARTMENT_ID = 30 OR Departments.DEPARTMENT_ID = 100
    ORDER BY DEPARTMENT_ID ASC;

#3
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, SALARY FROM Employees
	INNER JOIN Departments ON Employees.DEPARTMENT_ID = Departments.DEPARTMENT_ID
    WHERE (SALARY NOT BETWEEN 10000 AND 15000)
	AND (Departments.DEPARTMENT_ID = 30 OR Departments.DEPARTMENT_ID = 100);

#4
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, HIRE_DATE FROM Employees
	WHERE year(HIRE_DATE) = 1987;

#5
SELECT FIRST_NAME FROM Employees
	WHERE FIRST_NAME LIKE '%b%'
	AND FIRST_NAME LIKE '%c%';

#6
SELECT LAST_NAME, Jobs.JOB_TITLE, SALARY FROM Employees
	INNER JOIN Jobs ON Employees.JOB_ID = Jobs.JOB_ID
	WHERE (Employees.JOB_ID = 'IT_PROG' OR Employees.JOB_ID = 'SH_CLERK')
	AND (SALARY <> 4500.00 OR SALARY <> 10000.00 OR SALARY <> 15000.00)

#7
SELECT LAST_NAME FROM Employees
	WHERE LENGTH(FIRST_NAME) = 6;

#8
SELECT LAST_NAME FROM Employees
	WHERE SUBSTRING(LAST_NAME, 3, 1) = 'e';

#9
SELECT DISTINCT JOB_TITLE FROM Jobs
	INNER JOIN Employees ON Jobs.JOB_ID = Employees.JOB_ID
	WHERE Employees.JOB_ID NOT IN (SELECT DISTINCT Employees.JOB_ID FROM Employees)

SELECT DISTINCT JOB_TITLE FROM Jobs
	WHERE JOB_TITLE NOT IN (SELECT DISTINCT JOB_TITLE FROM Jobs INNER JOIN Employees ON Jobs.JOB_ID = Employees.JOB_ID);

#10
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, SALARY, round((0.15 * SALARY), 2) AS PF FROM Employees;

#11
SELECT * FROM Employees
	WHERE LAST_NAME IN ('BLAKE', 'SCOTT', 'KING', 'FORD');